# 1. Numpy Intro

In [ ]:
%matplotlib inline
%run mplimp.py

In [6]:
!pip install numpy

In [1]:
import numpy as np

In [3]:
np.random.seed(1337)

## 1.1 Basics of Matrices

In [4]:
x = np.array([1, 4, 3])
x

array([1, 4, 3])

In [5]:
y = np.array([[1, 4, 3],
              [9, 2, 7]])
y

array([[1, 4, 3],
       [9, 2, 7]])

In [6]:
x.shape

(3,)

In [7]:
y.shape

(2, 3)

In [8]:
z = np.array([[1, 2, 3]])
z.shape

(1, 3)

In [9]:
z = np.arange(1, 2000, 1)
z[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
z.shape

(1999,)

In [10]:
np.arange(0.5, 3, 0.5)

array([0.5, 1. , 1.5, 2. , 2.5])

In [12]:
np.arange(0.5, 10, 1).shape

(10,)

In [13]:
np.arange(0.5, 10, 1).reshape(5, 2).shape

(5, 2)

In [14]:
np.arange(0.5, 10, 1).reshape(5, 3).shape # will throw an error

ValueError: cannot reshape array of size 10 into shape (5,3)

In [15]:
np.linspace(3, 9, 10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [16]:
print(x)
print(x[1])
print(x[1:])

[1 4 3]
4
[4 3]


In [18]:
print(y)

[[1 4 3]
 [9 2 7]]


In [19]:
y[0, 1]

np.int64(4)

In [23]:
y[:,1] # all rows, 1 col

array([4, 2])

In [22]:
y[:,[1,2]] # all rows, col 1 and col 2

array([[4, 3],
       [2, 7]])

## 1.2. Matrix Operations

In [4]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [7]:
a.shape

(6,)

In [10]:
a[3] = 7
a

array([1, 2, 3, 7, 5, 6])

In [14]:
a[:5] = 1
a

array([1, 1, 1, 1, 1, 6])

In [15]:
a[1:5] = [5, 9, 6, 8]
a

array([1, 5, 9, 6, 8, 6])

In [4]:

# This is most useful
b = np.zeros((2, 2))
b[0, 0] = 1
b[0, 1] = 2
b[1, 0] = 3
b[1, 1] = 4

b

array([[1., 2.],
       [3., 4.]])

In [19]:
b.shape

(2, 2)

## 1.3. Array Operations

In [20]:
print(b)

[[1. 2.]
 [3. 4.]]


In [23]:
b + 2

array([[3., 4.],
       [5., 6.]])

In [22]:
2 * b

array([[2., 4.],
       [6., 8.]])

In [24]:
b ** 2

array([[ 1.,  4.],
       [ 9., 16.]])

In [25]:
sum(b)

array([4., 6.])

In [26]:
b.sum()

np.float64(10.0)

In [5]:
b

array([[1., 2.],
       [3., 4.]])

In [3]:
b.sum(axis=0)

array([4., 6.])

In [9]:
b.sum(axis=1)

array([3, 7])

In [5]:
b = np.array([[1, 2], [3, 4]])
print(b)
d = np.array([[3, 4], [5, 6]])
print(d)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


In [6]:
b + d

array([[ 4,  6],
       [ 8, 10]])

In [7]:
b * d

array([[ 3,  8],
       [15, 24]])

In [10]:
b.dot(d)

array([[13, 16],
       [29, 36]])

In [11]:
b ** d

array([[   1,   16],
       [ 243, 4096]])

In [12]:
b.T

array([[1, 3],
       [2, 4]])

In [19]:
a

array([1, 2, 3, 4, 5, 6])

In [20]:
a.T

array([1, 2, 3, 4, 5, 6])

In [23]:
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a.reshape(2, 3).shape

(2, 3)

In [24]:
a.reshape(2, 3).T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
a.reshape(2, 3).T.shape

(3, 2)

In [29]:
# Works on both scalars and arrays
print(np.sqrt(36))

x = [4, 9, 16, 25]
print(np.sqrt(x))

6.0
[2. 3. 4. 5.]


In [34]:
# Checking conditions
x = np.array([1, 2, 4, 5, 9, 3])
y = np.array([0, 1, 9, 3, 2, 3])

In [35]:
x > y

array([ True,  True, False,  True,  True, False])

In [36]:
x < y

array([False, False,  True, False, False, False])

# 2. Misc Operations with Numpy

In [3]:
import math

def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments: 
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """

    s = 1./(1. + math.e ** (-x))
    return s

In [38]:
basic_sigmoid(-1)

0.2689414213699951

In [39]:
basic_sigmoid(0)

0.5

In [40]:
basic_sigmoid(1)

0.7310585786300049

In [41]:
basic_sigmoid(8)

0.9996646498695336

In [4]:
x = [-1, 0, 3]
basic_sigmoid(x) # why? Because this function is designed for scalars, not vector

TypeError: bad operand type for unary -: 'list'

In [5]:
import numpy as np

x = [-1, 0, 3]
x = np.array(x)
basic_sigmoid(x)

array([0.26894142, 0.5       , 0.95257413])

## 2.1. Broadcasting

In [6]:
x = np.array([1, 2, 3])
x * 3

array([3, 6, 9])

In [7]:
x + 3

array([4, 5, 6])

*General Rules of Broadcasting:*</br>
    <p>Two dimensions are compatible, when</p>
    <ul>
        <li>They are equal, or</li>
        <li>one of them is 1</li>
    </ul>

In [9]:
x = np.arange(5)
x_r = x.reshape(5, 1)
y = np.ones(6)
z = np.ones((3, 4))

print("x = ",x)
print("x reshape = ",x_r)
print("y = ",y)
print("z = ",z)

print("Shapes: ")
print(x.shape)
print(x_r.shape)
print(y.shape)
print(z.shape)

x =  [0 1 2 3 4]
x reshape =  [[0]
 [1]
 [2]
 [3]
 [4]]
y =  [1. 1. 1. 1. 1. 1.]
z =  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shapes: 
(5,)
(5, 1)
(6,)
(3, 4)


In [11]:
x + y # it will not work, because the sizes are not equal, so it can't be broadcast

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [14]:
print("x_r = ",x_r)
print("y = ",y)

x_r =  [[0]
 [1]
 [2]
 [3]
 [4]]
y =  [1. 1. 1. 1. 1. 1.]


In [15]:
x_r + y # x_r is broadcast over the columns of y

array([[1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5.]])

In [13]:
y + x_r

array([[1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5.]])

In [16]:
np.array([1]) + y

array([2., 2., 2., 2., 2., 2.])

In [17]:
print(z)
z.shape

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


(3, 4)

In [18]:
x

array([0, 1, 2, 3, 4])

In [22]:
z + x # none of rule is satisfied

ValueError: operands could not be broadcast together with shapes (3,4) (5,) 

In [24]:
p = np.array([0, 1, 2, 4])
p.shape

(4,)

In [23]:
z + p # first rule of broadcast is satisfied here

array([[1., 2., 3., 5.],
       [1., 2., 3., 5.],
       [1., 2., 3., 5.]])

In [25]:
a = np.array([[0.0, 0.0, 0.0],
             [10.0, 10.0, 10.0],
             [20.0, 20.0, 20.0],
             [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])

In [26]:
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [27]:
a = np.array([[0.0, 0.0, 0.0, 0.0],
             [10.0, 10.0, 10.0, 10.0],
             [20.0, 20.0, 20.0, 20.0],
             [30.0, 30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0])

In [29]:
a + b # rules are not satisfied here

ValueError: operands could not be broadcast together with shapes (4,4) (2,) 

In [31]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

In [32]:
a + b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [33]:
print(a.shape, b.shape)

(4,) (3,)


In [36]:
a1 = a.reshape(4, 1)
a1

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [35]:
a1 + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [37]:
print(a1.shape, b.shape)

(4, 1) (3,)
