# 1. Numpy Intro

In [ ]:
%matplotlib inline
%run mplimp.py

In [6]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
np.random.seed(1337)

## 1.1 Basics of Matrices

In [4]:
x = np.array([1, 4, 3])
x

array([1, 4, 3])

In [5]:
y = np.array([[1, 4, 3],
              [9, 2, 7]])
y

array([[1, 4, 3],
       [9, 2, 7]])

In [6]:
x.shape

(3,)

In [7]:
y.shape

(2, 3)

In [8]:
z = np.array([[1, 2, 3]])
z.shape

(1, 3)

In [9]:
z = np.arange(1, 2000, 1)
z[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
z.shape

(1999,)

In [10]:
np.arange(0.5, 3, 0.5)

array([0.5, 1. , 1.5, 2. , 2.5])

In [12]:
np.arange(0.5, 10, 1).shape

(10,)

In [13]:
np.arange(0.5, 10, 1).reshape(5, 2).shape

(5, 2)

In [14]:
np.arange(0.5, 10, 1).reshape(5, 3).shape # will throw an error

ValueError: cannot reshape array of size 10 into shape (5,3)

In [15]:
np.linspace(3, 9, 10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [16]:
print(x)
print(x[1])
print(x[1:])

[1 4 3]
4
[4 3]


In [18]:
print(y)

[[1 4 3]
 [9 2 7]]


In [19]:
y[0, 1]

np.int64(4)

In [23]:
y[:,1] # all rows, 1 col

array([4, 2])

In [22]:
y[:,[1,2]] # all rows, col 1 and col 2

array([[4, 3],
       [2, 7]])

## 1.2. Matrix Operations

In [4]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [7]:
a.shape

(6,)

In [10]:
a[3] = 7
a

array([1, 2, 3, 7, 5, 6])

In [14]:
a[:5] = 1
a

array([1, 1, 1, 1, 1, 6])

In [15]:
a[1:5] = [5, 9, 6, 8]
a

array([1, 5, 9, 6, 8, 6])

In [17]:

# This is most useful
b = np.zeros((2, 2))
b[0, 0] = 1
b[0, 1] = 2
b[1, 0] = 3
b[1, 1] = 4

b

array([[1., 2.],
       [3., 4.]])

In [19]:
b.shape

(2, 2)

## 1.3. Array Operations

In [20]:
print(b)

[[1. 2.]
 [3. 4.]]


In [23]:
b + 2

array([[3., 4.],
       [5., 6.]])

In [22]:
2 * b

array([[2., 4.],
       [6., 8.]])

In [24]:
b ** 2

array([[ 1.,  4.],
       [ 9., 16.]])

In [25]:
sum(b)

array([4., 6.])

In [26]:
b.sum()

np.float64(10.0)