# 1. Linear Algebra Basics

## 1.1. Why Study Linear Algebra?

Think of Linear Algebra as basic operatons on vectors and matrices.

You've seen how we can represent groups of numbers in vectors and matrices. This makes them easier to manage. But once we do that, we need to be able to decide what add, subtract, multiply etc. mean on these "numbers".


So, we learn Linear Algebra so that we can do basic maths on these "numbers". We'll see examples of parallels here in a while.

## 1.2. Vectors

A <strong>vector</strong> in R<sup>n</sup> is an <i>n</i>-tuple. They can be horizontal and are called row vectors or vertical in which case they are called column vectors (the default).

## 1.3. Vector Norm

The norm of a vector is a measure of its length. There are many ways of defining the length of a vector depending on the metric used (i.e., the distance formula chosen). So, let's take a look at some distance formulae first.

### 1.3.1. Euclidean Distance

Euclidean distance is what you are already familiar with. The Euclidean distance between two points 
$$(x_1,y_1) $$ and $$(x_2,y_2)$$ is given as:

The Euclidean distance between two points is:

$$d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$$

For 3D points:

$$d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2 + (z_2 - z_1)^2}$$

If we take any vector and take it's x- and y-coordinates as its components, we can redefine the above like so:

This length is then called the L-2 Norm of the vector -- the stuff you know as the magnitude. The specific formula then is:

$$\|v\|_2 = \sqrt{\sum_{i} v_i^2}$$
where 
$$v_i$$
 are the elements of the vector 
v
.

## 1.4. Numpy Vectors Revisited

In [1]:
import numpy as np
from numpy.linalg import norm

In [3]:
# Row Vector
vector_row = np.array([[1, -5, 3, 2, 4]])
print(f'Row Vector: {vector_row}\n')

# Transpose of the Row vector
new_vector = vector_row.T
print(f'Transpose of Row Vector: {new_vector}\n')

norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf) # norm infinity

print('L_1 is: %.1f'%norm_1)
print('L_2 is: %.1f'%norm_2)

Row Vector: [[ 1 -5  3  2  4]]

Transpose of Row Vector: [[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]

L_1 is: 15.0
L_2 is: 7.4


### 1.4.1. Vector Operations

In [4]:
u = np.array([[0, 3, 2]])
v = np.array([[4, 1, 1]])
w = np.array([[0, -2, 0]])

x = 3*u - 2*v + 4*w
print(x)

[[-8 -1  4]]


In [7]:
print(u,'\n', v)

[[0 3 2]] 
 [[4 1 1]]


In [8]:
print(v.T)

[[4]
 [1]
 [1]]


In [10]:
u.dot(v) # bcz shapes are not aligned

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [11]:
print(u.shape)
print(v.shape)

(1, 3)
(1, 3)


In [14]:
u = np.array([[0, 3, 2]])
v = np.array([4, 1, 1]) # this is rank 1 tensor

x = u * v
print(x)

[[0 3 2]]


In [13]:
print(u, '\n', v)
print(v.T)

u.dot(v)

[[0 3 2]] 
 [4 1 1]
[4 1 1]


array([5])

In [15]:
print(u.shape)
print(v.shape)

(1, 3)
(3,)


## 1.5. Matrices

### 1.5.1 Matrix Multiplication

In [17]:
P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
print(P)
print(Q)
print(np.dot(P, Q))

[[1 7]
 [2 3]
 [5 0]]
[[2 6 3 1]
 [1 2 3 4]]
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


In [21]:
np.dot(Q, P) # can't do that, bcz dimensions are not aligned

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [20]:
print(P.shape)
print(Q.shape)

(3, 2)
(2, 4)


### 1.5.2. Determinants